version: "3.8"

services:
  postgres_dev:
    image: postgres:15
    container_name: typeorm_postgres_dev
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  postgres_test:
    image: postgres:15
    container_name: typeorm_postgres_test
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata_dev:
  pgdata_test:
